version: '3.8'
services:
  nuxt-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-frontend
    image: registry.gitlab.com/marektran/example-post-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NUXT_PROXY_URL=http://java-backend:8080