version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME} # Dependent on application.properties
    volumes:
      - local_pgdata_dev:/var/lib/postgresql/data

  pgadmin:
   image: dpage/pgadmin4
   container_name: pgadmin4
   restart: unless-stopped
   ports:
     - "8888:80"
   environment:
     PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
     PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASS}
   volumes:
     - pgadmin-data:/var/lib/pgadmin

  java-backend:
    restart: unless-stopped
    container_name: java-backend
    image: tranek/example-post-backend:latest
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - minio
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USR}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASS}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
      MINIO_SECRETKEY: ${MINIO_SECRETKEY}
      MINIO_POST_BUCKET_NAME: ${MINIO_POST_BUCKET_NAME}

  minio:
    restart: unless-stopped
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data_dev:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address :9001
  # This executes
  createbucket:
    image: minio/mc:latest
    container_name: createbucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 user password;
      /usr/bin/mc mb s3/static/;
      /usr/bin/mc anonymous set download s3/static;
      /usr/bin/mc admin user add s3 play 12345678;
      /usr/bin/mc admin policy set s3 readwrite user=play;
      "
    
volumes:
  minio_data_dev:
  local_pgdata_dev:
  pgadmin-data: